INSERT INTO usuarios (nombre, apellidos, username, alias, email, password, direccion, ciudad, pais, telefono) VALUES 
('Alejandro', 'Díaz Navarro', 'AlexD', 'ElFénix', 'alex.diaz@ejemplo.com', 'contraseña_hash_simulado_1', 'C/ Sol, 14', 'Madrid', 'España', '34600112233'),
('Laura', 'Gómez Martín', 'LauG', 'Gambito', 'laura.gomez@ejemplo.com', 'contraseña_hash_simulado_2', 'Av. Luna, 2A', 'Barcelona', 'España', '34611223344'),
('Carlos', 'Sánchez Pérez', 'SanCheez', 'MáquinaDeHacerDinero', 'carlos.sanchez@ejemplo.com', 'contraseña_hash_simulado_3', 'Pza. Mayor, 5', 'Valencia', 'España', '34622334455'),
('Sofía', 'Ruiz Fernández', 'SofiR', 'QueenOfHearts', 'sofia.ruiz@ejemplo.com', 'contraseña_hash_simulado_4', 'Ronda Exterior, 8', 'Sevilla', 'España', '34633445566'),
('Javier', 'Hernández López', 'JaviH', 'ElProfesor', 'javier.hernandez@ejemplo.com', 'contraseña_hash_simulado_5', 'C/ Río Ebro, 12', 'Bilbao', 'España', '34644556677'),
('Elena', 'Moreno Gil', 'Elenita', 'LaRoca', 'elena.moreno@ejemplo.com', 'contraseña_hash_simulado_6', 'Paseo de Gracia, 30', 'Barcelona', 'España', '34655667788'),
('Ricardo', 'Vidal Crespo', 'RichiVC', 'Torpedo77', 'ricardo.vidal@ejemplo.com', 'contraseña_hash_simulado_7', 'Av. del Mar, 7B', 'Málaga', 'España', '34666778899'),
('Patricia', 'Torres Vega', 'PatiTV', 'LadyLuck', 'patricia.torres@ejemplo.com', 'contraseña_hash_simulado_8', 'C/ Ancha, 25', 'Cádiz', 'España', '34677889900'),
('Miguel', 'López Castro', 'MigueLC', 'ElCaminante', 'miguel.lopez@ejemplo.com', 'contraseña_hash_simulado_9', 'C/ Girasol, 9', 'Murcia', 'España', '34688990011'),
('Andrea', 'Jiménez Ramos', 'AndreJR', 'Dynamo', 'andrea.jimenez@ejemplo.com', 'contraseña_hash_simulado_10', 'Paseo del Parque, 1', 'Palma', 'España', '34699001122'),
('Daniel', 'Muñoz Herrera', 'DaniMH', 'ElGladiador', 'daniel.munoz@ejemplo.com', 'contraseña_hash_simulado_11', 'Rambla del Mar, 100', 'Alicante', 'España', '34601234567'),
('Paula', 'Blanco Soto', 'PauB', 'TheStoic', 'paula.blanco@ejemplo.com', 'contraseña_hash_simulado_12', 'C/ Central, 3', 'Zaragoza', 'España', '34602345678'),
('Gabriel', 'Velasco Prieto', 'GaboVP', 'AceHigh', 'gabriel.velasco@ejemplo.com', 'contraseña_hash_simulado_13', 'C/ Estrella Polar, 22', 'León', 'España', '34603456789'),
('Isabel', 'Herrera Torres', 'IsaHT', 'TheCaller', 'isabel.herrera@ejemplo.com', 'contraseña_hash_simulado_14', 'Av. Dehesa, 5', 'Salamanca', 'España', '34604567890'),
('Fernando', 'Navarro Gil', 'FerNG', 'PokerFace', 'fernando.navarro@ejemplo.com', 'contraseña_hash_simulado_15', 'Pza. Olivo, 10', 'Córdoba', 'España', '34605678901'),
('Nuria', 'Pérez Sanz', 'NuriaPS', 'Bluffer', 'nuria.perez@ejemplo.com', 'contraseña_hash_simulado_16', 'Ronda del Este, 1', 'Burgos', 'España', '34606789012'),
('Roberto', 'Castro Díaz', 'RobCD', 'ElZar', 'roberto.castro@ejemplo.com', 'contraseña_hash_simulado_17', 'C/ Noche, 3', 'Gijón', 'España', '34607890123'),
('Silvia', 'Ramírez Vega', 'SilviaR', 'SilverQueen', 'silvia.ramirez@ejemplo.com', 'contraseña_hash_simulado_18', 'Av. Central, 45', 'Vigo', 'España', '34608901234'),
('Emilio', 'Soto Martín', 'EmiSM', 'SteadyHand', 'emilio.soto@ejemplo.com', 'contraseña_hash_simulado_19', 'Paseo de la Playa, 15', 'Santander', 'España', '34609012345'),
('Clara', 'Aguilar Muñoz', 'ClariAM', 'MissFold', 'clara.aguilar@ejemplo.com', 'contraseña_hash_simulado_20', 'C/ Estrecha, 18', 'Logroño', 'España', '34610123456'),
('Héctor', 'Blanco Cruz', 'HecBC', 'TheRock', 'hector.blanco@ejemplo.com', 'contraseña_hash_simulado_21', 'Ronda Sur, 9', 'Pamplona', 'España', '34611234567'),
('Lucía', 'García Torres', 'LuciGT', 'DiamondGirl', 'lucia.garcia@ejemplo.com', 'contraseña_hash_simulado_22', 'Av. Norte, 11', 'Toledo', 'España', '34612345678'),
('Mario', 'Ruiz Sáez', 'MarioRS', 'CrazyMario', 'mario.ruiz@ejemplo.com', 'contraseña_hash_simulado_23', 'C/ Almenara, 23', 'Cáceres', 'España', '34613456789'),
('Diana', 'López Fernández', 'DianaLF', 'TheHuntress', 'diana.lopez@ejemplo.com', 'contraseña_hash_simulado_24', 'Pza. Jardín, 6', 'Albacete', 'España', '34614567890'),
('Pedro', 'Morales Pérez', 'PeteMP', 'MrPots', 'pedro.morales@ejemplo.com', 'contraseña_hash_simulado_25', 'Ronda Este, 14', 'Huelva', 'España', '34615678901'),
('Eva', 'Núñez Ramos', 'EvaNR', 'LittleBlind', 'eva.nunez@ejemplo.com', 'contraseña_hash_simulado_26', 'C/ De la Paz, 7', 'Jaén', 'España', '34616789012'),
('Andrés', 'Jiménez Soler', 'AndyJS', 'TheDragon', 'andres.jimenez@ejemplo.com', 'contraseña_hash_simulado_27', 'Av. Principal, 50', 'Girona', 'España', '34617890123'),
('Vanesa', 'Martín Gil', 'VaneMG', 'Whisper', 'vanesa.martin@ejemplo.com', 'contraseña_hash_simulado_28', 'Paseo Marítimo, 33', 'Tarragona', 'España', '34618901234'),
('Óscar', 'Díaz López', 'OscarDL', 'TheGambler', 'oscar.diaz@ejemplo.com', 'contraseña_hash_simulado_29', 'C/ Del Sol, 1A', 'Lleida', 'España', '34619012345'),
('Rocío', 'Gutiérrez Vega', 'RocioGV', 'RoyalFlush', 'rocio.gutierrez@ejemplo.com', 'contraseña_hash_simulado_30', 'Av. Dehesa, 2', 'Badajoz', 'España', '34620123456'),
('Guillermo', 'Paz Soto', 'GuillePS', 'Waller', 'guillermo.paz@ejemplo.com', 'contraseña_hash_simulado_31', 'Ronda Interior, 12', 'Ourense', 'España', '34621234567'),
('Irene', 'Romero Cruz', 'IreneRC', 'Zenith', 'irene.romero@ejemplo.com', 'contraseña_hash_simulado_32', 'C/ Larga, 44', 'Lugo', 'España', '34622345678'),
('Jesús', 'Vargas Torres', 'JesusVT', 'ElTigre', 'jesus.vargas@ejemplo.com', 'contraseña_hash_simulado_33', 'Pza. Central, 7', 'Cáceres', 'España', '34623456789'),
('Sara', 'Méndez Herrera', 'SaraMH', 'ColdCaller', 'sara.mendez@ejemplo.com', 'contraseña_hash_simulado_34', 'Av. Del Río, 19', 'Zamora', 'España', '34624567890'),
('Felipe', 'Blanco Rico', 'FelipeBR', 'TheGrinder', 'felipe.blanco@ejemplo.com', 'contraseña_hash_simulado_35', 'C/ Nueva, 31', 'Segovia', 'España', '34625678901'),
('Marta', 'Herrero Sanz', 'MartaHS', 'Madness', 'marta.herrero@ejemplo.com', 'contraseña_hash_simulado_36', 'Ronda Norte, 5', 'Ávila', 'España', '34626789012'),
('Rubén', 'Gómez Vidal', 'RubenGV', 'QuickFold', 'ruben.gomez@ejemplo.com', 'contraseña_hash_simulado_37', 'Paseo del Campo, 8', 'Soria', 'España', '34627890123'),
('Carmen', 'Soto Díez', 'CarmiSD', 'FinalTable', 'carmen.soto@ejemplo.com', 'contraseña_hash_simulado_38', 'Av. Principal, 10', 'Palencia', 'España', '34628901234'),
('Tomás', 'López Nieto', 'TomiLN', 'TheMaverick', 'tomas.lopez@ejemplo.com', 'contraseña_hash_simulado_39', 'C/ del Sol Naciente, 2', 'Valladolid', 'España', '34629012345'),
('Natalia', 'Pérez Ruiz', 'NataPR', 'IceWoman', 'natalia.perez@ejemplo.com', 'contraseña_hash_simulado_40', 'Pza. De la Villa, 11', 'Ciudad Real', 'España', '34630123456'),
('Álvaro', 'Martínez Gil', 'AlvaroMG', 'KingPin', 'alvaro.martinez@ejemplo.com', 'contraseña_hash_simulado_41', 'Ronda del Parque, 20', 'Guadalajara', 'España', '34631234567'),
('Beatriz', 'Herrera Díaz', 'BeaHD', 'TightBea', 'beatriz.herrera@ejemplo.com', 'contraseña_hash_simulado_42', 'C/ Río Duero, 3', 'Cuenca', 'España', '34632345678');